apiVersion: v1
kind: ConfigMap
metadata:
  name: flowable-config
  labels:
    app: flowable
data:
    SERVER_PORT: "8080"
    SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
    SPRING_DATASOURCE_URL: jdbc:postgresql://reeling-monkey-postgresql.default.svc.cluster.local:5432/postgres
    SPRING_DATASOURCE_USERNAME: postgres
    SPRING_DATASOURCE_PASSWORD: EvxvRe87BB

    # full url of the IDM app; used for server to server communication
    FLOWABLE_COMMON_APP_IDM-URL: http://flowfest.knowprocess.com/flowable-idm
    FLOWABLE_COMMON_APP_IDM-REDIRECT-URL: http://flowfest.knowprocess.com/flowable-idm
    # IDM admin user (when running with default configuration: admin)
    FLOWABLE_COMMON_APP_IDM-ADMIN_USER: admin
    # IDM admin password (when running with default configuration: test)
    FLOWABLE_COMMON_APP_IDM-ADMIN_PASSWORD: test
